"use client";

import { useState } from "react";
import FileUploader from "./components/FileUploader";
import ExportGuide from "./components/ExportGuide";
import ExportHistory from "./components/ExportHistory";
import { saveExport } from "@/lib/exportHistory";

export default function HomePage() {
  const [darkMode, setDarkMode] = useState(true);
  const [processedData, setProcessedData] = useState<{
    profileText: string;
    profileJson: any;
    source?: "chatgpt" | "claude" | "gemini" | "unknown";
  } | null>(null);
  const [exportFormats, setExportFormats] = useState<{
    claude: string;
    chatgpt: string;
    gemini: string;
  } | null>(null);

  const mainClasses = darkMode
    ? "min-h-screen w-full flex flex-col items-center px-6 py-12 dark-gradient text-slate-50"
    : "min-h-screen w-full flex flex-col items-center px-6 py-12 light-gradient text-neutral-900";

  const handleDataProcessed = (data: { profileText: string; profileJson: any; source?: string }) => {
    setProcessedData({
      profileText: data.profileText,
      profileJson: data.profileJson,
      source: data.source as "chatgpt" | "claude" | "gemini" | "unknown" | undefined,
    });

    // Auto-save to export history
    saveExport({
      source: (data.source as "chatgpt" | "claude" | "gemini" | "unknown") || "unknown",
      profileJson: data.profileJson,
      profileText: data.profileText,
    });

    // Generate LLM-specific formats
    generateExportFormats(data);
  };

  const generateExportFormats = (data: { profileText: string; profileJson: any }) => {
    const profile = data.profileJson?.profile || {};

    // Claude Project Knowledge format
    const claudeFormat = `# AI Memory Context

## About Me
${profile.basic?.name ? `Name: ${profile.basic.name}` : ''}
${profile.basic?.location ? `Location: ${profile.basic.location}` : ''}

## My Preferences
${profile.preferences?.likes ? `I like: ${profile.preferences.likes.join(', ')}` : ''}
${profile.preferences?.dislikes ? `I dislike: ${profile.preferences.dislikes.join(', ')}` : ''}
${profile.preferences?.tone ? `Preferred communication tone: ${profile.preferences.tone}` : ''}

## My Work
${profile.work?.roles ? `Roles: ${profile.work.roles.join(', ')}` : ''}
${profile.work?.industries ? `Industries: ${profile.work.industries.join(', ')}` : ''}
${profile.work?.current_focus ? `Current focus: ${profile.work.current_focus.join(', ')}` : ''}

## My Goals
${profile.goals?.short_term ? `Short-term: ${profile.goals.short_term.join(', ')}` : ''}
${profile.goals?.long_term ? `Long-term: ${profile.goals.long_term.join(', ')}` : ''}

## My Skills
${profile.skills ? profile.skills.join(', ') : ''}

## My Constraints
${profile.constraints ? profile.constraints.join(', ') : ''}

## Communication Style
${profile.communication_style ? profile.communication_style.join(', ') : ''}

---
This context was generated by Continuum - portable AI memory across models.
`;

    // ChatGPT Custom Instructions format
    const chatgptFormat = `**What would you like ChatGPT to know about you to provide better responses?**

${profile.basic?.name ? `My name is ${profile.basic.name}. ` : ''}
${profile.work?.roles ? `I work as ${profile.work.roles.join(' and ')}. ` : ''}
${profile.work?.current_focus ? `Currently focused on: ${profile.work.current_focus.join(', ')}. ` : ''}
${profile.goals?.short_term ? `My short-term goals: ${profile.goals.short_term.join(', ')}. ` : ''}
${profile.skills ? `My skills include: ${profile.skills.join(', ')}. ` : ''}
${profile.constraints ? `Constraints I work with: ${profile.constraints.join(', ')}. ` : ''}

**How would you like ChatGPT to respond?**

${profile.preferences?.tone ? `Use a ${profile.preferences.tone} tone. ` : ''}
${profile.communication_style ? `Communication style: ${profile.communication_style.join(', ')}. ` : ''}
${profile.preferences?.likes ? `I appreciate: ${profile.preferences.likes.join(', ')}. ` : ''}
${profile.preferences?.dislikes ? `Please avoid: ${profile.preferences.dislikes.join(', ')}. ` : ''}

Generated by Continuum.
`;

    // Gemini Gems format (structured context)
    const geminiFormat = `You are a personalized AI assistant with knowledge about this user.

USER CONTEXT:
${JSON.stringify(profile, null, 2)}

INSTRUCTIONS:
- Adapt your responses to their background, goals, and communication style
- Respect their preferences (likes/dislikes)
- Consider their constraints when making suggestions
- Match their preferred tone: ${profile.preferences?.tone || 'professional'}

Generated by Continuum - portable AI memory.
`;

    setExportFormats({
      claude: claudeFormat,
      chatgpt: chatgptFormat,
      gemini: geminiFormat,
    });
  };

  const downloadFile = (content: string, filename: string) => {
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <main className={mainClasses}>
      {/* Hero */}
      <header className="w-full max-w-4xl flex flex-col items-center text-center mb-12 animate-fade-in">
        <div className="h-20 w-20 rounded-3xl bg-gradient-to-br from-purple-500 to-indigo-600 flex items-center justify-center text-white text-3xl font-bold shadow-2xl mb-6">
          🧠
        </div>
        <h1 className="text-6xl font-bold mb-4 gradient-text">
          Continuum
        </h1>
        <p className="text-2xl opacity-90 mb-2">
          Portable AI Memory Layer
        </p>
        <p className="text-lg opacity-60 max-w-2xl">
          Your AI context, portable across all models. Never start from zero again.
        </p>

        <div className="flex items-center gap-4 mt-6">
          <span className={`px-4 py-2 rounded-full text-sm font-medium ${
            darkMode ? 'glass text-purple-300' : 'glass-light text-purple-700'
          }`}>
            🔒 Zero-Knowledge Encrypted
          </span>
          <button
            onClick={() => setDarkMode(!darkMode)}
            className={`px-4 py-2 rounded-full text-sm font-medium transition-smooth ${
              darkMode ? 'glass hover:bg-white/10' : 'glass-light hover:bg-black/5'
            }`}
          >
            {darkMode ? '☀️ Light' : '🌙 Dark'}
          </button>
        </div>
      </header>

      {/* How it works */}
      {!processedData && (
        <section className={`w-full max-w-4xl mb-12 ${
          darkMode ? 'glass' : 'glass-light'
        } rounded-3xl p-8 transition-smooth`}>
          <h2 className="text-2xl font-bold mb-6 text-center">How It Works</h2>
          <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
            <div className="text-center">
              <div className="text-4xl mb-3">📤</div>
              <div className="font-semibold mb-2">1. Export</div>
              <div className="text-sm opacity-70">Download your AI chat history</div>
            </div>
            <div className="text-center">
              <div className="text-4xl mb-3">🔄</div>
              <div className="font-semibold mb-2">2. Convert</div>
              <div className="text-sm opacity-70">We extract & encrypt your context</div>
            </div>
            <div className="text-center">
              <div className="text-4xl mb-3">📥</div>
              <div className="font-semibold mb-2">3. Download</div>
              <div className="text-sm opacity-70">Get files for each LLM</div>
            </div>
            <div className="text-center">
              <div className="text-4xl mb-3">✨</div>
              <div className="font-semibold mb-2">4. Import</div>
              <div className="text-sm opacity-70">Use in any AI model</div>
            </div>
          </div>
        </section>
      )}

      {/* Export Guide */}
      {!processedData && (
        <section className="w-full max-w-4xl mb-8">
          <ExportGuide darkMode={darkMode} />
        </section>
      )}

      {/* Export History */}
      {!processedData && (
        <section className="w-full max-w-4xl mb-8">
          <ExportHistory onMergedProfile={handleDataProcessed} />
        </section>
      )}

      {/* Upload Section */}
      {!processedData && (
        <section className="w-full max-w-4xl">
          <FileUploader onResult={handleDataProcessed} />
        </section>
      )}

      {/* Results Section */}
      {processedData && exportFormats && (
        <div className="w-full max-w-4xl space-y-8 animate-fade-in">
          {/* Success Message */}
          <section className={`${
            darkMode ? 'glass' : 'glass-light'
          } rounded-3xl p-8 text-center`}>
            <div className="text-6xl mb-4">✅</div>
            <h2 className="text-3xl font-bold mb-3">Your Memory is Ready!</h2>
            <p className="text-lg opacity-80">
              Download the formats below and import into your preferred AI model.
            </p>
          </section>

          {/* Download Cards */}
          <div className={`grid gap-6 ${
            processedData.source === "unknown"
              ? "grid-cols-1 md:grid-cols-3"
              : "grid-cols-1 md:grid-cols-2"
          }`}>
            {/* Claude - hide if source is claude */}
            {processedData.source !== "claude" && (
              <div className={`${
                darkMode ? 'glass' : 'glass-light'
              } rounded-3xl p-6 hover-glow transition-smooth`}>
                <div className="text-4xl mb-4">🤖</div>
                <h3 className="text-xl font-bold mb-2">Claude</h3>
                <p className="text-sm opacity-70 mb-4">
                  For Claude Projects & Knowledge
                </p>
                <button
                  onClick={() => downloadFile(exportFormats.claude, 'claude-memory.txt')}
                  className={`w-full px-4 py-3 rounded-xl font-medium transition-smooth ${
                    darkMode
                      ? 'bg-purple-600 hover:bg-purple-500 text-white'
                      : 'bg-purple-500 hover:bg-purple-600 text-white'
                  }`}
                >
                  📥 Download
                </button>
              </div>
            )}

            {/* ChatGPT - hide if source is chatgpt */}
            {processedData.source !== "chatgpt" && (
              <div className={`${
                darkMode ? 'glass' : 'glass-light'
              } rounded-3xl p-6 hover-glow transition-smooth`}>
                <div className="text-4xl mb-4">💬</div>
                <h3 className="text-xl font-bold mb-2">ChatGPT</h3>
                <p className="text-sm opacity-70 mb-4">
                  For Custom Instructions
                </p>
                <button
                  onClick={() => downloadFile(exportFormats.chatgpt, 'chatgpt-memory.txt')}
                  className={`w-full px-4 py-3 rounded-xl font-medium transition-smooth ${
                    darkMode
                      ? 'bg-purple-600 hover:bg-purple-500 text-white'
                      : 'bg-purple-500 hover:bg-purple-600 text-white'
                  }`}
                >
                  📥 Download
                </button>
              </div>
            )}

            {/* Gemini - hide if source is gemini */}
            {processedData.source !== "gemini" && (
              <div className={`${
                darkMode ? 'glass' : 'glass-light'
              } rounded-3xl p-6 hover-glow transition-smooth`}>
                <div className="text-4xl mb-4">✨</div>
                <h3 className="text-xl font-bold mb-2">Gemini</h3>
                <p className="text-sm opacity-70 mb-4">
                  For Gems & Context
                </p>
                <button
                  onClick={() => downloadFile(exportFormats.gemini, 'gemini-memory.txt')}
                  className={`w-full px-4 py-3 rounded-xl font-medium transition-smooth ${
                    darkMode
                      ? 'bg-purple-600 hover:bg-purple-500 text-white'
                      : 'bg-purple-500 hover:bg-purple-600 text-white'
                  }`}
                >
                  📥 Download
                </button>
              </div>
            )}
          </div>

          {/* Import Instructions */}
          <section className={`${
            darkMode ? 'glass' : 'glass-light'
          } rounded-3xl p-8`}>
            <h2 className="text-2xl font-bold mb-6">📖 How to Import</h2>

            <div className="space-y-6">
              {/* Claude Instructions */}
              <div>
                <h3 className="font-bold text-lg mb-2">🤖 Claude</h3>
                <ol className="list-decimal list-inside space-y-1 text-sm opacity-80">
                  <li>Open Claude.ai</li>
                  <li>Create a new Project</li>
                  <li>Add <code className="px-2 py-1 rounded bg-black/20">claude-memory.txt</code> to Project Knowledge</li>
                  <li>Start chatting! Claude now has your full context.</li>
                </ol>
              </div>

              {/* ChatGPT Instructions */}
              <div>
                <h3 className="font-bold text-lg mb-2">💬 ChatGPT</h3>
                <ol className="list-decimal list-inside space-y-1 text-sm opacity-80">
                  <li>Open ChatGPT</li>
                  <li>Go to Settings → Personalization → Custom Instructions</li>
                  <li>Paste content from <code className="px-2 py-1 rounded bg-black/20">chatgpt-memory.txt</code></li>
                  <li>Save. ChatGPT now knows your context!</li>
                </ol>
              </div>

              {/* Gemini Instructions */}
              <div>
                <h3 className="font-bold text-lg mb-2">✨ Gemini</h3>
                <ol className="list-decimal list-inside space-y-1 text-sm opacity-80">
                  <li>Open Gemini</li>
                  <li>Create a new Gem</li>
                  <li>Paste content from <code className="px-2 py-1 rounded bg-black/20">gemini-memory.txt</code></li>
                  <li>Use your Gem for personalized responses!</li>
                </ol>
              </div>
            </div>
          </section>

          {/* Convert Another */}
          <div className="text-center">
            <button
              onClick={() => {
                setProcessedData(null);
                setExportFormats(null);
              }}
              className={`px-6 py-3 rounded-xl font-medium transition-smooth ${
                darkMode
                  ? 'glass hover:bg-white/10'
                  : 'glass-light hover:bg-black/5'
              }`}
            >
              ← Convert Another Export
            </button>
          </div>
        </div>
      )}

      {/* Footer */}
      <footer className="mt-16 text-center opacity-50 text-sm">
        <p>Built with 🧠 for AI context portability</p>
      </footer>
    </main>
  );
}
