"use client";

import { useState } from "react";
import FileUploader from "./components/FileUploader";
import ExportHistory from "./components/ExportHistory";
import InfinityAnimation from "./components/InfinityAnimation";
import { saveExport } from "@/lib/exportHistory";
import { ArrowRight, Download, Upload, Sparkles, Shield, Layers, Moon, Sun } from "lucide-react";

export default function HomePage() {
  const [darkMode, setDarkMode] = useState(true);
  const [currentPage, setCurrentPage] = useState<"home" | "about">("home");
  const [processedData, setProcessedData] = useState<{
    profileText: string;
    profileJson: any;
    source?: "chatgpt" | "claude" | "gemini" | "unknown";
  } | null>(null);
  const [exportFormats, setExportFormats] = useState<{
    claude: string;
    chatgpt: string;
    gemini: string;
  } | null>(null);

  const mainClasses = darkMode
    ? "min-h-screen w-full bg-black text-white"
    : "min-h-screen w-full bg-white text-black";

  const handleDataProcessed = (data: { profileText: string; profileJson: any; source?: string }) => {
    setProcessedData({
      profileText: data.profileText,
      profileJson: data.profileJson,
      source: data.source as "chatgpt" | "claude" | "gemini" | "unknown" | undefined,
    });

    // Auto-save to export history
    saveExport({
      source: (data.source as "chatgpt" | "claude" | "gemini" | "unknown") || "unknown",
      profileJson: data.profileJson,
      profileText: data.profileText,
    });

    // Generate LLM-specific formats
    generateExportFormats(data);
  };

  const generateExportFormats = (data: { profileText: string; profileJson: any }) => {
    const profile = data.profileJson?.profile || {};

    // Claude Project Knowledge format
    const claudeFormat = `# AI Memory Context

## About Me
${profile.basic?.name ? `Name: ${profile.basic.name}` : ''}
${profile.basic?.location ? `Location: ${profile.basic.location}` : ''}

## My Preferences
${profile.preferences?.likes ? `I like: ${profile.preferences.likes.join(', ')}` : ''}
${profile.preferences?.dislikes ? `I dislike: ${profile.preferences.dislikes.join(', ')}` : ''}
${profile.preferences?.tone ? `Preferred communication tone: ${profile.preferences.tone}` : ''}

## My Work
${profile.work?.roles ? `Roles: ${profile.work.roles.join(', ')}` : ''}
${profile.work?.industries ? `Industries: ${profile.work.industries.join(', ')}` : ''}
${profile.work?.current_focus ? `Current focus: ${profile.work.current_focus.join(', ')}` : ''}

## My Goals
${profile.goals?.short_term ? `Short-term: ${profile.goals.short_term.join(', ')}` : ''}
${profile.goals?.long_term ? `Long-term: ${profile.goals.long_term.join(', ')}` : ''}

## My Skills
${profile.skills ? profile.skills.join(', ') : ''}

## My Constraints
${profile.constraints ? profile.constraints.join(', ') : ''}

## Communication Style
${profile.communication_style ? profile.communication_style.join(', ') : ''}

---
This context was generated by Continuum - portable AI memory across models.
`;

    // ChatGPT Custom Instructions format
    const chatgptFormat = `**What would you like ChatGPT to know about you to provide better responses?**

${profile.basic?.name ? `My name is ${profile.basic.name}. ` : ''}
${profile.work?.roles ? `I work as ${profile.work.roles.join(' and ')}. ` : ''}
${profile.work?.current_focus ? `Currently focused on: ${profile.work.current_focus.join(', ')}. ` : ''}
${profile.goals?.short_term ? `My short-term goals: ${profile.goals.short_term.join(', ')}. ` : ''}
${profile.skills ? `My skills include: ${profile.skills.join(', ')}. ` : ''}
${profile.constraints ? `Constraints I work with: ${profile.constraints.join(', ')}. ` : ''}

**How would you like ChatGPT to respond?**

${profile.preferences?.tone ? `Use a ${profile.preferences.tone} tone. ` : ''}
${profile.communication_style ? `Communication style: ${profile.communication_style.join(', ')}. ` : ''}
${profile.preferences?.likes ? `I appreciate: ${profile.preferences.likes.join(', ')}. ` : ''}
${profile.preferences?.dislikes ? `Please avoid: ${profile.preferences.dislikes.join(', ')}. ` : ''}

Generated by Continuum.
`;

    // Gemini Gems format (structured context)
    const geminiFormat = `You are a personalized AI assistant with knowledge about this user.

USER CONTEXT:
${JSON.stringify(profile, null, 2)}

INSTRUCTIONS:
- Adapt your responses to their background, goals, and communication style
- Respect their preferences (likes/dislikes)
- Consider their constraints when making suggestions
- Match their preferred tone: ${profile.preferences?.tone || 'professional'}

Generated by Continuum - portable AI memory.
`;

    setExportFormats({
      claude: claudeFormat,
      chatgpt: chatgptFormat,
      gemini: geminiFormat,
    });
  };

  const downloadFile = (content: string, filename: string) => {
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  // Navigation
  const NavLink = ({ page, children }: { page: typeof currentPage; children: React.ReactNode }) => (
    <button
      onClick={() => setCurrentPage(page)}
      className={`px-4 py-2 text-sm font-medium transition-all ${
        currentPage === page
          ? darkMode
            ? "text-white border-b-2 border-white"
            : "text-black border-b-2 border-black"
          : darkMode
          ? "text-gray-400 hover:text-white"
          : "text-gray-600 hover:text-black"
      }`}
    >
      {children}
    </button>
  );

  return (
    <main className={mainClasses}>
      {/* Navigation */}
      <nav className={`fixed top-0 left-0 right-0 z-50 border-b ${
        darkMode ? "border-white/10 bg-black/80" : "border-black/10 bg-white/80"
      } backdrop-blur-xl`}>
        <div className="max-w-7xl mx-auto px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="text-2xl font-bold">∞</div>
            <span className="text-xl font-bold">Continuum</span>
          </div>

          <div className="flex items-center gap-6">
            <NavLink page="home">Home</NavLink>
            <NavLink page="about">About</NavLink>

            <button
              onClick={() => setDarkMode(!darkMode)}
              className={`ml-4 w-10 h-10 rounded-full flex items-center justify-center border transition-all ${
                darkMode
                  ? "border-white/20 hover:bg-white/10"
                  : "border-black/20 hover:bg-black/5"
              }`}
              aria-label={darkMode ? "Switch to light mode" : "Switch to dark mode"}
            >
              {darkMode ? <Sun className="w-5 h-5" /> : <Moon className="w-5 h-5" />}
            </button>
          </div>
        </div>
      </nav>

      {/* Content */}
      <div className="pt-20">
        {currentPage === "home" && (
          <HomePage_Content
            darkMode={darkMode}
            processedData={processedData}
            exportFormats={exportFormats}
            handleDataProcessed={handleDataProcessed}
            downloadFile={downloadFile}
            setProcessedData={setProcessedData}
            setExportFormats={setExportFormats}
          />
        )}
        {currentPage === "about" && <AboutPage darkMode={darkMode} />}
      </div>
    </main>
  );
}

// Home Page Content
function HomePage_Content({
  darkMode,
  processedData,
  exportFormats,
  handleDataProcessed,
  downloadFile,
  setProcessedData,
  setExportFormats,
}: any) {
  return (
    <>
      {/* Hero Section with Infinity Animation */}
      {!processedData && (
        <section className="min-h-screen flex flex-col items-center justify-center px-6 relative">
          {/* Infinity Animation - Takes up most of screen */}
          <div className="w-full max-w-4xl h-[60vh] mb-12">
            <InfinityAnimation darkMode={darkMode} />
          </div>

          {/* Headline */}
          <div className="text-center max-w-3xl">
            <h1 className="text-6xl md:text-7xl font-bold mb-6">
              Your AI Memory,
              <br />
              <span className={darkMode ? "text-gray-400" : "text-gray-600"}>
                Infinitely Portable
              </span>
            </h1>
            <p className={`text-xl md:text-2xl mb-12 ${
              darkMode ? "text-gray-400" : "text-gray-600"
            }`}>
              Never start from zero again. Export your conversations from any AI,
              import anywhere. Your context, your control.
            </p>

            {/* CTA */}
            <button
              onClick={() => {
                const uploadSection = document.getElementById("upload-section");
                uploadSection?.scrollIntoView({ behavior: "smooth" });
              }}
              className={`group px-8 py-4 rounded-full border-2 font-medium text-lg inline-flex items-center gap-2 transition-all ${
                darkMode
                  ? "border-white hover:bg-white hover:text-black"
                  : "border-black hover:bg-black hover:text-white"
              }`}
            >
              Get Started
              <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
            </button>
          </div>
        </section>
      )}

      {/* How It Works */}
      {!processedData && (
        <section className={`py-24 px-6 border-t ${
          darkMode ? "border-white/10" : "border-black/10"
        }`}>
          <div className="max-w-6xl mx-auto">
            <h2 className="text-4xl md:text-5xl font-bold text-center mb-16">
              How It Works
            </h2>

            <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
              <div className="text-center">
                <div className={`w-16 h-16 rounded-full border-2 mx-auto mb-6 flex items-center justify-center ${
                  darkMode ? "border-white/20" : "border-black/20"
                }`}>
                  <Upload className="w-8 h-8" />
                </div>
                <h3 className="text-xl font-bold mb-3">1. Export</h3>
                <p className={darkMode ? "text-gray-400" : "text-gray-600"}>
                  Download your chat history from ChatGPT, Claude, or Gemini
                </p>
              </div>

              <div className="text-center">
                <div className={`w-16 h-16 rounded-full border-2 mx-auto mb-6 flex items-center justify-center ${
                  darkMode ? "border-white/20" : "border-black/20"
                }`}>
                  <Sparkles className="w-8 h-8" />
                </div>
                <h3 className="text-xl font-bold mb-3">2. Extract</h3>
                <p className={darkMode ? "text-gray-400" : "text-gray-600"}>
                  We extract your preferences, goals, and context with AI
                </p>
              </div>

              <div className="text-center">
                <div className={`w-16 h-16 rounded-full border-2 mx-auto mb-6 flex items-center justify-center ${
                  darkMode ? "border-white/20" : "border-black/20"
                }`}>
                  <Shield className="w-8 h-8" />
                </div>
                <h3 className="text-xl font-bold mb-3">3. Encrypt</h3>
                <p className={darkMode ? "text-gray-400" : "text-gray-600"}>
                  Zero-knowledge encryption keeps your data private
                </p>
              </div>

              <div className="text-center">
                <div className={`w-16 h-16 rounded-full border-2 mx-auto mb-6 flex items-center justify-center ${
                  darkMode ? "border-white/20" : "border-black/20"
                }`}>
                  <Download className="w-8 h-8" />
                </div>
                <h3 className="text-xl font-bold mb-3">4. Import</h3>
                <p className={darkMode ? "text-gray-400" : "text-gray-600"}>
                  Import your memory into any AI model instantly
                </p>
              </div>
            </div>
          </div>
        </section>
      )}

      {/* Upload Section */}
      {!processedData && (
        <section id="upload-section" className={`py-24 px-6 border-t ${
          darkMode ? "border-white/10" : "border-black/10"
        }`}>
          <div className="max-w-4xl mx-auto space-y-8">
            <div className="text-center mb-12">
              <h2 className="text-4xl md:text-5xl font-bold mb-6">
                Start Building Your Memory
              </h2>
              <p className={`text-xl ${darkMode ? "text-gray-400" : "text-gray-600"}`}>
                Upload your AI chat exports to create your portable identity graph
              </p>
            </div>

            <ExportHistory onMergedProfile={handleDataProcessed} />
            <FileUploader onResult={handleDataProcessed} />
          </div>
        </section>
      )}

      {/* Results Section */}
      {processedData && exportFormats && (
        <div className="min-h-screen py-24 px-6">
          <div className="max-w-4xl mx-auto space-y-16">
            {/* Success Message */}
            <div className="text-center">
              <div className="text-6xl mb-6">✓</div>
              <h2 className="text-5xl font-bold mb-4">Memory Extracted</h2>
              <p className={`text-xl ${darkMode ? "text-gray-400" : "text-gray-600"}`}>
                Download your portable AI memory for each platform
              </p>
            </div>

            {/* Download Cards */}
            <div className={`grid gap-6 ${
              processedData.source === "unknown"
                ? "grid-cols-1 md:grid-cols-3"
                : "grid-cols-1 md:grid-cols-2"
            }`}>
              {/* Claude */}
              {processedData.source !== "claude" && (
                <button
                  onClick={() => downloadFile(exportFormats.claude, 'claude-memory.txt')}
                  className={`p-8 rounded-3xl transition-all text-left ${
                    darkMode ? "glass-card-dark" : "glass-card-light"
                  }`}
                >
                  <Layers className="w-12 h-12 mb-4" />
                  <h3 className="text-2xl font-bold mb-2">Claude</h3>
                  <p className={`mb-4 ${darkMode ? "text-gray-400" : "text-gray-600"}`}>
                    For Claude Projects & Knowledge
                  </p>
                  <div className="flex items-center gap-2 font-medium">
                    <Download className="w-5 h-5" />
                    Download
                  </div>
                </button>
              )}

              {/* ChatGPT */}
              {processedData.source !== "chatgpt" && (
                <button
                  onClick={() => downloadFile(exportFormats.chatgpt, 'chatgpt-memory.txt')}
                  className={`p-8 rounded-3xl transition-all text-left ${
                    darkMode ? "glass-card-dark" : "glass-card-light"
                  }`}
                >
                  <Sparkles className="w-12 h-12 mb-4" />
                  <h3 className="text-2xl font-bold mb-2">ChatGPT</h3>
                  <p className={`mb-4 ${darkMode ? "text-gray-400" : "text-gray-600"}`}>
                    For Custom Instructions
                  </p>
                  <div className="flex items-center gap-2 font-medium">
                    <Download className="w-5 h-5" />
                    Download
                  </div>
                </button>
              )}

              {/* Gemini */}
              {processedData.source !== "gemini" && (
                <button
                  onClick={() => downloadFile(exportFormats.gemini, 'gemini-memory.txt')}
                  className={`p-8 rounded-3xl transition-all text-left ${
                    darkMode ? "glass-card-dark" : "glass-card-light"
                  }`}
                >
                  <Shield className="w-12 h-12 mb-4" />
                  <h3 className="text-2xl font-bold mb-2">Gemini</h3>
                  <p className={`mb-4 ${darkMode ? "text-gray-400" : "text-gray-600"}`}>
                    For Gems & Context
                  </p>
                  <div className="flex items-center gap-2 font-medium">
                    <Download className="w-5 h-5" />
                    Download
                  </div>
                </button>
              )}
            </div>

            {/* Convert Another */}
            <div className="text-center pt-12">
              <button
                onClick={() => {
                  setProcessedData(null);
                  setExportFormats(null);
                }}
                className={`px-6 py-3 rounded-full border-2 font-medium transition-all ${
                  darkMode
                    ? "border-white/20 hover:bg-white/10"
                    : "border-black/20 hover:bg-black/5"
                }`}
              >
                ← Process Another Export
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  );
}

// About Page
function AboutPage({ darkMode }: { darkMode: boolean }) {
  return (
    <div className="min-h-screen py-24 px-6">
      <div className="max-w-4xl mx-auto">
        <h1 className="text-6xl font-bold mb-12">About Continuum</h1>

        <div className="space-y-8 text-lg">
          <p className={darkMode ? "text-gray-300" : "text-gray-700"}>
            Continuum is your portable AI memory layer. We believe your conversations
            with AI shouldn't be locked into a single platform.
          </p>

          <p className={darkMode ? "text-gray-300" : "text-gray-700"}>
            Every conversation you have with ChatGPT, Claude, or Gemini teaches these
            models about you—your preferences, communication style, goals, and expertise.
            But this context doesn't transfer when you switch models.
          </p>

          <p className={darkMode ? "text-gray-300" : "text-gray-700"}>
            Continuum solves this. Export your history from any AI, and we'll extract
            a portable identity graph you can import anywhere. Your memory becomes truly
            yours—infinite and continuous across all models.
          </p>

          <div className={`p-8 rounded-2xl border-2 mt-12 ${
            darkMode ? "border-white/20" : "border-black/20"
          }`}>
            <h2 className="text-3xl font-bold mb-4">Why Continuum?</h2>
            <ul className={`space-y-3 ${darkMode ? "text-gray-300" : "text-gray-700"}`}>
              <li>• <strong>Zero-Knowledge Encryption:</strong> Your data stays private</li>
              <li>• <strong>Model Agnostic:</strong> Works with all major AI platforms</li>
              <li>• <strong>Incremental Building:</strong> Merge multiple exports over time</li>
              <li>• <strong>Open Source:</strong> Transparent and community-driven</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
}

